# Generated by Django 5.2.4 on 2025-07-13 19:16

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('code_id', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('1', 'Stage 1'), ('2', 'Stage 2'), ('3', 'Stage 3'), ('4', 'Stage 4'), ('5', 'Stage 5')], default='1', max_length=1)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bank_name', models.CharField(blank=True, choices=[('Access', 'Access Bank'), ('First', 'First Bank'), ('GTB', 'Guaranty Trust Bank'), ('Zenith', 'Zenith Bank'), ('UBA', 'United Bank for Africa'), ('Ecobank', 'Ecobank'), ('Fidelity', 'Fidelity Bank'), ('Stanbic', 'Stanbic IBTC'), ('Union', 'Union Bank'), ('Other', 'Other')], max_length=50, null=True)),
                ('bank_account_no', models.CharField(blank=True, max_length=20, null=True)),
                ('referral_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('referral_code_id', models.CharField(blank=True, max_length=50, null=True)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=255, null=True)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('next_of_kin_email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('next_of_kin_address', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
    ]
