# Generated by Django 5.2.4 on 2025-07-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='no_referrals',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
